name: Open WebUI
description: Run the Open WebUI within Cloudera AI Workbench
author: Cloudera Inc.
specification_version: 1.0
prototype_version: 1.0
date: "2024-12-29"

environment_variables:
  INFERENCE_SERVICE_BASE_URL:
    default: "https://go01-aws-ml-serving.go01-dem.ylcu-atmi.cloudera.site/namespaces/serving-default/endpoints/llama-3-1-8b-instruct/v1"
    description: "Base URL for the Cloudera Inference service model you are using"
    required: true

runtimes:
  - editor: PBJ Workbench
    kernel: Python 3.11
    edition: Standard

tasks:
  - type: run_session
    name: Install Dependencies
    script: install_dependencies.py
    kernel: python3
    cpu: 2
    memory: 8

  - type: start_application
    name: Open WebUI
    subdomain: open-webui
    script: run_app.py
    short_summary: Start Open WebUI application
    cpu: 2
    memory: 4
    environment_variables:
      TASK_TYPE: START_APPLICATION